appName: myapp

replicaCount: 3

image:
  repository: ghcr.io/horizon-school-of-digital-technologies/simple-webapp-color
  tag: latest

containerPort: 8080

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "250m"

ingress:
  host: azizjedidi.color.horizon-workspaces.com

service:
  port: 80

persistence:
  size: 1Gi
  storageClass: gp2
